plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.example'
version = '0.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.apache.commons:commons-lang3:3.14.0'
    implementation 'org.apache.commons:commons-collections4:4.4'
    implementation 'org.yaml:snakeyaml:2.2'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml'
    implementation 'org.seleniumhq.selenium:selenium-java:4.19.1'
    implementation 'io.github.bonigarcia:webdrivermanager:5.7.0'
    implementation 'io.cucumber:cucumber-java:7.16.1'
    implementation 'io.cucumber:cucumber-spring:7.16.1'
    implementation 'io.cucumber:cucumber-junit-platform-engine:7.16.1'
    implementation 'com.company.qa:qa-core:1.0.3'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.cucumber:cucumber-junit:7.16.1'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Test) {
    useJUnitPlatform()
}

tasks.register('runCucumber', JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'io.cucumber.core.cli.Main'

    def tags = project.findProperty('cucumber.tags') ?: ''

    args = [
            '--plugin', 'pretty',
            '--plugin', 'json:build/cucumber.json',
            '--plugin', 'junit:build/cucumber.xml',
            '--glue', 'com.example.webtestingia.steps',
            '--glue', 'com.example.webtestingia.hooks',
            'src/test/resources/features'
    ]

    if (tags) {
        args += ['--tags', tags]
    }
}
